"""last revision

Revision ID: 18bb533bb784
Revises: 9a21edf81f73
Create Date: 2023-04-24 16:04:51.719352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bb533bb784'
down_revision = '9a21edf81f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
